config/routes.rb
Rails.application.routes.draw do
  get '/auth/google_oauth2/callback' => 'sessions#create'
  resources :questions, expect: [:destroy]
  resources :users, only: [:index, :new, :create, :update, :destroy]
  resources :settings, only: [:index]
  resources :surveys, only: [] do
    resources :batch_answers, controller: 'surveys/batch_answers', only: [:new, :create]
    resource :completed, controller: 'surveys/completed', only: [:show]
  end
  root to: 'home#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  MAX_SCORE = 4

  validates :user, :question, :survey, presence: true
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: MAX_SCORE }, allow_nil: true

  belongs_to :user
  belongs_to :question
  belongs_to :survey

  scope :answered, -> { where.not(score: nil) }
  scope :since, ->(since) { where('created_at >= ?', since) }
  scope :on_flexible_question, -> { includes(:question).where(questions: { regularity: 'flexible'}) }
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :email, :uid, presence: true
  validates :uid, uniqueness: true

  has_many :answers

  def answers_for_survey(survey)
    answers.where(survey: survey)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  REGULARITIES = %w(fixed flexible)

  validates :body, :regularity, presence: true
  validates :regularity, inclusion: { in: REGULARITIES }

  has_many :answers
  has_many :users, -> { uniq }, through: :answers

  scope :fixed_regularity, -> { where regularity: 'fixed' }
  scope :flexible_regularity, -> { where regularity: 'flexible' }

  def scores(since = Time.at(0))
    answers.since(since).pluck(:score).compact
  end

  def respondents(since = Time.at(0))
    answers.since(since).map(&:user).uniq
  end

  def happiness_score(since = Time.at(0))
    scores = self.scores(since)
    return 0 if scores.none?
    average = (scores.sum.to_f / scores.count)
    score = average * (100 / Answer::MAX_SCORE)
    score.round
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation { self.email = self.email.downcase }

  validates :email, presence: true, uniqueness: true

  has_many :answers
  has_many :surveys, -> { uniq }, through: :answers

  scope :active,   -> { where(deleted_at: nil) }
  scope :inactive, -> { where.not(deleted_at: nil) }

  def answers_for_survey(survey)
    answers.where(survey: survey)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :set_current_user

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  protected

  def set_current_user
    @current_user = User.find_by_id(session[:current_user_id])
  end

  def authenticate_user!
    store_location
    redirect_to '/auth/google_oauth2' if @current_user.nil?
  end

  def store_location
    return unless request.get? || request.xhr?
    session[:previous_url] = request.fullpath
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def not_authorized
    render file: "#{Rails.root}/public/403.html", status: 403, layout: false
  end

  def pundit_user
    @current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize @current_user
    @questions = Question.all
  end

  def show
    authorize @current_user
    @question = Question.find(params[:id])
  end

  def new
    authorize @current_user
    @question = Question.new
  end

  def create
    authorize @current_user
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = t('created')
      redirect_to questions_path
    else
      flash.now[:error] = t('error')
      render :new
    end
  end

  def edit
    authorize @current_user
    @question = Question.find(params[:id])
  end

  def update
    authorize @current_user
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to questions_path, notice: t('updated')
    else
      flash.now[:error] = t('error')
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:body, :regularity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    google_auth = request.env['omniauth.auth']

    if user = User.active.find_by_email(google_auth.info.email.downcase)
      session[:current_user_id] = user.id
      flash[:notice] = t('authenticated')
      redirect_to session[:previous_url] || root_path
    else
      session[:current_user_id] = nil
      not_authorized
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize @current_user
  end
end

app/controllers/surveys/batch_answers_controller.rb
class Surveys::BatchAnswersController < ApplicationController
  before_filter :authenticate_user!

  def new
    answers = @current_user.answers_for_survey(params[:survey_id])
    @answers = prefil_provided_answer(answers)

    not_found if @answers.none?
  end

  def create
    result = Answer.update(create_answer_params.keys, create_answer_params.values).reject{ |a| a.errors.empty? }
    if result.empty?
      flash[:notice] = t('created')
      redirect_to survey_completed_path
    else
      answer_ids = result.collect{ |a| a.id }
      flash[:error] = answer_ids.join(', ')
      redirect_to new_survey_batch_answer_path
    end
  end

  private

  def new_answer_params
    params.permit(:answer_id, :score)
  end

  def create_answer_params
    params.require(:answers)
  end

  def prefil_provided_answer(answers)
    provided_answer = answers.find(new_answer_params[:answer_id])
    provided_answer.score = new_answer_params[:score]
    index = answers.index(provided_answer)
    answers[index] = provided_answer
    answers
  end
end

app/controllers/surveys/completed_controller.rb
class Surveys::CompletedController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize @current_user
    @active_users   = User.active.all.order(:email)
    @inactive_users = User.inactive.all.order(:email)
  end

  def new
    authorize @current_user
    @user = User.new
  end

  def create
    authorize @current_user
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = t('created')
      redirect_to users_path
    else
      flash.now[:error] = t('error')
      render :new
    end
  end

  def update
    authorize @current_user
    user = User.find(params[:id])

    if user.update(user_params)
      redirect_to users_path, notice: t('updated')
    else
      redirect_to users_path, error: t('error')
    end
  end

  def destroy
    authorize @current_user
    user = User.find(params[:id])
    if user != @current_user && user.update(deleted_at: Date.today, admin: false)
      flash[:notice] = t('deleted')
    else
      flash[:error] = t('error')
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :deleted_at, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  GOOD_ENOUGH_SCORE = ENV.fetch('GOOD_ENOUGH_SCORE').to_i

  def user_authenticated?
    @current_user.present?
  end

  def colored_happiness_score(score)
    if score > 0 && score < GOOD_ENOUGH_SCORE
      klass = 'red'
    elsif score >= GOOD_ENOUGH_SCORE
      klass = 'green'
    end
    klass
  end

  def weekdays_to_names(wdays)
    wdays.map{ |wday| Date::DAYNAMES[wday.to_i] }.compact.join(', ')
  end
end

app/views/home/index.html.haml
= render 'layouts/nav' if user_authenticated?

%section.center-box
  = image_tag 'happy.svg', width: 64, height: 64, class: 'center-box__image'
  - unless user_authenticated?
    %a{ href: '/auth/google_oauth2', class: 'button button-primary center-box__button' }= t('login')

app/views/layouts/_flash.html.haml
- flash.each do |flash|
  .row
    .six-columns.flash{ class: "flash-#{flash.first}" }
      = flash.last

app/views/layouts/_nav.html.haml
%nav.navbar
  %ul
    %li.navbar__item= link_to t('questions'), questions_path, class: 'btn'
    %li.navbar__item= link_to t('users'), users_path, class: 'btn'
    %li.navbar__item= link_to t('settings'), settings_path, class: 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: 'utf-8' }
    %title= ENV['NAME']
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    %link{ href: '//fonts.googleapis.com/css?family=Raleway:400,300,600', rel: 'stylesheet', type: 'text/css' }
    = csrf_meta_tags

  %body
    .container
      = render 'layouts/flash'
      = yield

app/views/questions/_form.html.haml
.row
  .six.columns
    = f.label :body
    = f.text_field :body, required: true, class: 'u-full-width'

.row
  .six.columns
    = f.label :regularity
    = f.select :regularity, Question::REGULARITIES, {}

app/views/questions/_question.html.haml
%tr
  %td
    = link_to question.body, question_path(question)
  %td
    = link_to edit_question_path(question) do
      = image_tag 'fi-pencil.svg', widht: 16, height: 16
  %td
    .u-pull-right
      - hs = question.happiness_score
      %div{class: colored_happiness_score(hs) }= hs

app/views/questions/edit.html.haml
= render 'layouts/nav'

= form_for @question do |form|

  - if @question.errors.any?
    %ul
      - @question.errors.full_messages.each do |message|
        %li= message

  = render partial: 'form', locals: { f: form }

  %button.button.button-primary{ type: 'submit' }= t('save')

app/views/questions/index.html.haml
= render 'layouts/nav'

= link_to new_question_path, class: 'button u-pull-right' do
  = image_tag 'fi-magnifying-glass.svg', widht: 16, height: 16, class: 'img-align'
  = t('new')

%table.u-full-width
  %thead
    %tr
      %th{ colspan: 2 }= t('fixed')
      %th hs
  %tbody
  = render partial: 'question', collection: @questions.fixed_regularity

%table.u-full-width
  %thead
    %tr
      %th{ colspan: 2 }= t('flexible')
      %th hs
  %tbody
  = render partial: 'question', collection: @questions.flexible_regularity

app/views/questions/new.html.haml
= render 'layouts/nav'

= form_for @question do |form|

  - if @question.errors.any?
    %ul
      - @question.errors.full_messages.each do |message|
        %li= message

  = render partial: 'form', locals: { f: form }

  %button.button.button-primary{ type: 'submit' }= t('save')

app/views/questions/show.html.haml
= render 'layouts/nav'

%h1= @question.body

.u-cf

%h4= t('last_7_days')

.row
  .one-third.column
    - hs = @question.happiness_score(7.days.ago)
    %h2{ class: colored_happiness_score(hs) }= number_to_percentage(hs, precision: 0)
    %h5= t('happiness_score')
  .one-third.column
    %h2= @question.scores(7.days.ago).count
    %h5= t('total_answers')
  .one-third.column
    %h2= @question.respondents(7.days.ago).count
    %h5= t('total_users')

%h4= t('overall')

.row
  .one-third.column
    - hs = @question.happiness_score
    %h2{ class: colored_happiness_score(hs) }= number_to_percentage(hs, precision: 0)
    %h5= t('happiness_score')
  .one-third.column
    %h2= @question.scores.count
    %h5= t('total_answers')
  .one-third.column
    %h2= @question.respondents.count
    %h5= t('total_users')

app/views/settings/index.html.haml
= render 'layouts/nav'

%table.u-full-width
  %tbody
    %tr
      %th= t('good_enough_score')
      %td= ENV['GOOD_ENOUGH_SCORE']
    %tr
      %th= t('google_client_id')
      %td= ENV['GOOGLE_CLIENT_ID']
    %tr
      %th= t('google_client_secret')
      %td= '*' * ENV['GOOGLE_CLIENT_SECRET'].length
    %tr
      %th= t('host')
      %td= ENV['HOST']
    %tr
      %th= t('mailer_address')
      %td= ENV['MAILER_ADDRESS']
    %tr
      %th= t('mailer_authentication')
      %td= ENV['MAILER_AUTHENTICATION']
    %tr
      %th= t('mailer_domain')
      %td= ENV['MAILER_DOMAIN']
    %tr
      %th= t('mailer_password')
      %td= '*' * ENV['MAILER_PASSWORD'].length
    %tr
      %th= t('mailer_port')
      %td= ENV['MAILER_PORT']
    %tr
      %th= t('mailer_user_name')
      %td= ENV['MAILER_USER_NAME']
    %tr
      %th= t('name')
      %td= ENV['NAME']
    %tr
      %th= t('number_of_flexible_questions_per_survey')
      %td= ENV['NUMBER_OF_FLEXIBLE_QUESTIONS_PER_SURVEY']
    %tr
      %th= t('postmaster')
      %td= ENV['POSTMASTER']
    %tr
      %th= t('protocol')
      %td= ENV['PROTOCOL']
    %tr
      %th= t('send_survey_at_days')
      %td= weekdays_to_names(ENV['SEND_SURVEY_AT_DAYS'].split(','))

app/views/surveys/batch_answers/new.html.haml
= form_for :batch_answers, url: survey_batch_answers_path do |f|
  - @answers.each do |answer|
    = fields_for 'answers[]', answer do |g|
      - klass = 'hide' if answer.score.present?
      .row.answer{ class: klass }= answer.question.body

      .row.answer{ class: klass }
        .two.columns
          = g.radio_button :score, 4
          = g.label :score, '4', value: 4 do
            = image_tag 'delighted.png', alt: t('delighted')

        .two.columns
          = g.radio_button :score, 3
          = g.label :score, '3', value: 3 do
            = image_tag 'happy.png', alt: t('happy')

        .two.columns
          = g.radio_button :score, 2
          = g.label :score, '2', value: 2 do
            = image_tag 'neutral.png', alt: t('neutral')

        .two.columns
          = g.radio_button :score, 1
          = g.label :score, '1', value: 1 do
            = image_tag 'sad.png', alt: t('sad')

        .two.columns
          = g.radio_button :score, 0
          = g.label :score, value: 0 do
            = image_tag 'angry.png', alt: t('angry')

  %button.button{ type: 'submit' }= t('save')

app/views/surveys/completed/show.html.haml
.center-box
  = image_tag 'happy.svg', width: 128, height: 128
  %h1 Thank you

app/views/users/_form.html.haml
.row
  .six.columns
    = f.label :email
    = f.email_field :email, required: true, class: 'u-full-width'

app/views/users/index.html.haml
= render 'layouts/nav'

= link_to new_user_path, class: 'button u-pull-right' do
  = image_tag 'fi-torso.svg', widht: 16, height: 16, class: 'img-align'
  = t('new')

%table.u-full-width
  %thead
    %tr
      %th{ colspan: 4 }= t('active')
  %tbody
  - @active_users.each do |user|
    %tr
      %td
        = user.email
      %td
        - if user != @current_user
          = link_to user_path(user), method: :delete do
            = image_tag 'fi-trash.svg', widht: 16, height: 16
          = form_for user, html: { class: 'icon-form' } do |form|
            = form.hidden_field :admin, value: !user.admin?
            = image_submit_tag 'fi-torso-business.svg', widht: 16, height: 16
      %td
        - if user.admin?
          %code= t('admin')
      %td
        .u-pull-right
          = user.surveys.count
          %small= t('surveys')

%table.u-full-width
  %thead
    %tr.muted
      %th{ colspan: 3 }= t('inactive')
  %tbody
  - @inactive_users.each do |user|
    %tr.muted
      %td= user.email
      %td
        = form_for user, html: { class: 'undelete-button'} do |form|
          = form.hidden_field :deleted_at, value: ''
          = image_submit_tag 'fi-refresh.svg', widht: 16, height: 16
      %td
        .u-pull-right
          = user.surveys.count
          %small= t('surveys')

app/views/users/new.html.haml
= render 'layouts/nav'

= form_for @user do |form|

  - if @user.errors.any?
    %ul
      - @user.errors.full_messages.each do |message|
        %li= message

  = render partial: 'form', locals: { f: form }

  %button.button.button-primary{ type: 'submit' }= t('save')